contact_links:
  - name: "\U0001F4AC Slack"
    url: https://join.slack.com/t/aeon-neuro/shared_invite/zt-2k4qs8mjb-ZZs~6P0MdF8kGf9cUQzKSg
    about: For all other questions and general chat, come chat with the aeon-neuro community on Slack!
  - name: "\u2709\uFE0F Email"
    url: https://mailxto.com/jbp3ave49x
    about: Send an email to the aeon developers at contact@aeon-toolkit.org. Checked periodically.
  - name: "\u2709\uFE0F CoC Report"
    url: https://www.aeon-toolkit.org/en/latest/code_of_conduct.html
    about: Report an incident to the Code of Conduct Workgroup.
