"""Detach-ROCKET channel selector using aeon MiniRocket transforms.

The Sequential Feature Detachment procedure is adapted from the Detach-ROCKET
reference implementation at https://github.com/gon-uri/detach_rocket.
"""

__maintainer__ = ["TonyBagnall"]
__all__ = ["DetachRocket", "DetachRocketChannelSelector"]

import math

import numpy as np
from aeon.transformations.collection.channel_selection.base import (
    BaseChannelSelector,
)
from aeon.transformations.collection.convolution_based import MiniRocket
from sklearn.linear_model import RidgeClassifier, RidgeClassifierCV
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.utils import check_random_state


class DetachRocketChannelSelector(BaseChannelSelector):
    """Select channels using independently fitted Detach-ROCKET models.

    Each channel is transformed with aeon's MiniRocket implementation. Sequential
    Feature Detachment (SFD) repeatedly removes the least important convolutional
    features and refits a ridge classifier. The validation accuracy of the model
    selected by the Detach-ROCKET accuracy/size trade-off is used as the channel
    score.

    Parameters
    ----------
    proportion : float, default=0.4
        Proportion of channels to retain. The number retained is rounded up.
    n_kernels : int, default=10000
        Number of MiniRocket features requested per channel.
    trade_off : float, default=0.1
        Weight given to feature reduction when selecting a point on the SFD curve.
        A value of zero selects using validation accuracy only.
    validation_size : float, default=0.33
        Proportion of training cases used to score the SFD models.
    drop_percentage : float, default=0.05
        Proportion of currently available features removed at each SFD step.
    max_detach_steps : int, default=150
        Maximum number of SFD pruning steps.
    smoothing_points : int, default=3
        Width of the moving average used by the original Detach-ROCKET
        model-size objective.
    alphas : array-like or None, default=None
        Ridge regularisation strengths. If None, 20 values between 1e-10 and 1e10
        are used.
    multilabel_type : {"norm", "max", "avg"}, default="max"
        Method used to combine class-specific ridge coefficients.
    n_jobs : int, default=1
        Number of threads used by MiniRocket.
    random_state : int or None, default=None
        Random seed used for validation splitting and MiniRocket.

    Attributes
    ----------
    channels_selected_ : np.ndarray
        Indices of selected channels, ordered by descending score.
    channel_scores_ : np.ndarray
        Detach-ROCKET validation score for every input channel.
    channel_feature_proportions_ : np.ndarray
        Proportion of MiniRocket features retained for each channel's selected model.
    channel_sfd_curves_ : list of np.ndarray
        Validation accuracy curve generated by SFD for each channel.

    References
    ----------
    .. [1] Uribarri, G., Barone, F., Ansuini, A., and Fransen, E.
       "Detach-ROCKET: Sequential feature selection for time series classification
       with random convolutional kernels." Data Mining and Knowledge Discovery,
       2024.
    """

    _tags = {
        "requires_y": True,
        "capability:multivariate": True,
        "capability:multithreading": True,
        "capability:unequal_length": False,
        "algorithm_type": "convolution",
    }

    def __init__(
        self,
        proportion=0.4,
        n_kernels=10000,
        trade_off=0.1,
        validation_size=0.33,
        drop_percentage=0.05,
        max_detach_steps=150,
        smoothing_points=3,
        alphas=None,
        multilabel_type="max",
        n_jobs=1,
        random_state=None,
    ):
        self.proportion = proportion
        self.n_kernels = n_kernels
        self.trade_off = trade_off
        self.validation_size = validation_size
        self.drop_percentage = drop_percentage
        self.max_detach_steps = max_detach_steps
        self.smoothing_points = smoothing_points
        self.alphas = alphas
        self.multilabel_type = multilabel_type
        self.n_jobs = n_jobs
        self.random_state = random_state
        super().__init__()

    def _fit(self, X, y):
        self._validate_parameters()
        rng = check_random_state(self.random_state)
        alphas = (
            np.logspace(-10, 10, 20)
            if self.alphas is None
            else np.asarray(self.alphas, dtype=float)
        )

        train_indices, validation_indices = train_test_split(
            np.arange(len(y)),
            test_size=self.validation_size,
            random_state=rng,
            stratify=y,
        )

        n_channels = X.shape[1]
        self.channel_scores_ = np.empty(n_channels, dtype=float)
        self.channel_feature_proportions_ = np.empty(n_channels, dtype=float)
        self.channel_sfd_curves_ = []
        self.channel_percentage_vectors_ = []

        for channel in range(n_channels):
            seed = rng.randint(np.iinfo(np.int32).max)
            transformer = MiniRocket(
                n_kernels=self.n_kernels,
                n_jobs=self.n_jobs,
                random_state=seed,
            )
            X_transformed = transformer.fit_transform(X[:, channel : channel + 1])

            scaler = StandardScaler()
            X_transformed = scaler.fit_transform(np.asarray(X_transformed))
            X_train = X_transformed[train_indices]
            X_validation = X_transformed[validation_indices]
            y_train = y[train_indices]
            y_validation = y[validation_indices]

            full_classifier = RidgeClassifierCV(alphas=alphas)
            full_classifier.fit(X_transformed, y)
            classifier = RidgeClassifier(alpha=full_classifier.alpha_)
            classifier.fit(X_train, y_train)

            percentages, validation_scores = _feature_detachment(
                classifier=classifier,
                X_train=X_train,
                X_validation=X_validation,
                y_train=y_train,
                y_validation=y_validation,
                drop_percentage=self.drop_percentage,
                max_steps=self.max_detach_steps,
                multilabel_type=self.multilabel_type,
            )
            selected = _select_detach_model(
                percentages=percentages,
                validation_scores=validation_scores,
                trade_off=self.trade_off,
                smoothing_points=self.smoothing_points,
            )

            self.channel_scores_[channel] = validation_scores[selected]
            self.channel_feature_proportions_[channel] = percentages[selected]
            self.channel_sfd_curves_.append(validation_scores)
            self.channel_percentage_vectors_.append(percentages)

        n_selected = math.ceil(n_channels * self.proportion)
        self.channels_selected_ = np.argsort(-self.channel_scores_)[:n_selected]
        return self

    def _validate_parameters(self):
        if not 0 < self.proportion <= 1:
            raise ValueError("proportion must be in the range (0, 1].")
        if self.n_kernels <= 0:
            raise ValueError("n_kernels must be greater than zero.")
        if self.trade_off < 0:
            raise ValueError("trade_off must be greater than or equal to zero.")
        if not 0 < self.validation_size < 1:
            raise ValueError("validation_size must be in the range (0, 1).")
        if not 0 < self.drop_percentage < 1:
            raise ValueError("drop_percentage must be in the range (0, 1).")
        if self.max_detach_steps < 1:
            raise ValueError("max_detach_steps must be at least one.")
        if self.smoothing_points < 1:
            raise ValueError("smoothing_points must be at least one.")
        if self.multilabel_type not in {"norm", "max", "avg"}:
            raise ValueError("multilabel_type must be 'norm', 'max', or 'avg'.")

    @classmethod
    def _get_test_params(cls, parameter_set="default"):
        """Return a small parameter set for estimator tests."""
        return {
            "proportion": 0.5,
            "n_kernels": 84,
            "max_detach_steps": 3,
            "alphas": [0.1, 1.0],
            "random_state": 0,
        }


def _feature_detachment(
    classifier,
    X_train,
    X_validation,
    y_train,
    y_validation,
    drop_percentage,
    max_steps,
    multilabel_type,
):
    """Run Sequential Feature Detachment and return its validation curve."""
    n_features = X_train.shape[1]
    keep_percentage = 1 - drop_percentage
    feature_counts = np.unique(
        (np.power(keep_percentage, np.arange(max_steps)) * n_features).astype(int)
    )
    feature_counts = feature_counts[feature_counts > 0][::-1]
    percentages = feature_counts / n_features

    feature_importance = _ridge_feature_importance(classifier.coef_, multilabel_type)
    validation_scores = np.empty(len(feature_counts), dtype=float)

    for i, n_selected in enumerate(feature_counts):
        selected = np.argsort(feature_importance)[-n_selected:]
        classifier.fit(X_train[:, selected], y_train)
        validation_scores[i] = classifier.score(X_validation[:, selected], y_validation)

        updated_importance = _ridge_feature_importance(
            classifier.coef_, multilabel_type
        )
        feature_importance[:] = 0
        feature_importance[selected] = updated_importance

    return percentages, validation_scores


def _ridge_feature_importance(coefficients, multilabel_type):
    coefficients = np.asarray(coefficients)
    if coefficients.ndim == 1:
        return np.abs(coefficients)
    if multilabel_type == "norm":
        return np.linalg.norm(coefficients, axis=0, ord=2)
    if multilabel_type == "max":
        return np.linalg.norm(coefficients, axis=0, ord=np.inf)
    return np.linalg.norm(coefficients, axis=0, ord=1)


def _select_detach_model(percentages, validation_scores, trade_off, smoothing_points=3):
    full_score = validation_scores[0]
    if np.isclose(full_score, 0):
        relative_scores = validation_scores
    else:
        relative_scores = validation_scores / full_score
    smoothing_box = np.ones(smoothing_points) / smoothing_points
    smoothed_scores = np.convolve(relative_scores, smoothing_box, mode="same")
    objective = smoothed_scores + trade_off * (1 - percentages)
    return int(np.argmax(objective))


DetachRocket = DetachRocketChannelSelector
