name: PR Opened

on:
  pull_request_target:
    types: [opened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  # based on the scikit-learn 1.3.1 PR labelers
  labeler:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/utilities

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PyGithub
        run: pip install -Uq PyGithub

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.PR_APP_ID }}
          private-key: ${{ secrets.PR_APP_KEY }}

      - name: Label pull request
        id: label-pr
        run: python .github/utilities/pr_labeler.py ${{ steps.app-token.outputs.token }}
        env:
          CONTEXT_GITHUB: ${{ toJson(github) }}

      - name: Write pull request comment
        run: python .github/utilities/pr_open_commenter.py ${{ steps.app-token.outputs.token }} ${{ steps.label-pr.outputs.title-labels }} ${{ steps.label-pr.outputs.title-labels-new }} ${{ steps.label-pr.outputs.content-labels }} ${{ steps.label-pr.outputs.content-labels-status }}
        env:
          CONTEXT_GITHUB: ${{ toJson(github) }}
